export const TRACKS_STATS_REQUEST = "TRACKS_STATS_REQUEST";
export const TRACKS_STATS_ERROR = "TRACKS_STATS_ERROR";
export const TRACKS_STATS_SUCCESS = "TRACKS_STATS_SUCCESS";

export const TRACKS_PLAYBACKS_REQUEST = "TRACKS_PLAYBACKS_REQUEST";
export const TRACKS_PLAYBACKS_ERROR = "TRACKS_PLAYBACKS_ERROR";
export const TRACKS_PLAYBACKS_SUCCESS = "TRACKS_PLAYBACKS_SUCCESS";

export const TRACK_STATS_REQUEST = "TRACK_STATS_REQUEST";
export const TRACK_STATS_ERROR = "TRACK_STATS_ERROR";
export const TRACK_STATS_SUCCESS = "TRACK_STATS_SUCCESS";

export const GENRES_STATS_REQUEST = "GENRES_STATS_REQUEST";
export const GENRES_STATS_ERROR = "GENRES_STATS_ERROR";
export const GENRES_STATS_SUCCESS = "GENRES_STATS_SUCCESS";
