export const FETCHING_USER_DATA = "FETCHING_USER_DATA";
export const FETCHING_ERROR = "FETCHING_ERROR";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SUBMIT_USER_DATA = "SUBMIT_USER_DATA";
