export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const RESET_STORE_AND_LOG_OUT = "RESET_STORE_AND_LOG_OUT";

export const userTypes = {
  ALL: "ALL",
  FOLLOWERS: "FOLLOWERS",
  FOLLOWING: "FOLLOWING",
  RECOMMENDED: "RECOMMENDED",
  POPULAR: "POPULAR",
};
