export const USER_AGENT_REQUEST = "USER_AGENT_REQUEST";
export const USER_AGENT_ERROR = "USER_AGENT_ERROR";
export const USER_AGENT_SUCCESS = "USER_AGENT_SUCCESS";

export const COORDINATES_REQUEST = "COORDINATES_REQUEST";
export const COORDINATES_ERROR = "COORDINATES_ERROR";
export const COORDINATES_SUCCESS = "COORDINATES_SUCCESS";
